version: '3.8'
services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tic_tac_toe_db
    ports:
      - "5430:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

#  datastore-service:
#    image: "datastore-service"
#    links:
#      - postgres
#
#  client:
#    image: "client"