-- Схема, сгенерированная hibernate в тесте HomeworkTest

create sequence hibernate_sequence start with 1 increment by 1;

create table clients (
    id bigint generated by default as identity,
    name varchar(255),
    address_id bigint,
    primary key (id)
);

create table addresses (
    id bigint generated by default as identity,
    street varchar(255),
    primary key (id)
);

create table phones (
    id bigint not null,
    number varchar(255),
    client_id bigint,
    primary key (id)
);

alter table clients add constraint FK21gyuophuha3vq8t1os4x2jtl foreign key (address_id) references addresses;

alter table phones add constraint FK2ovgkw92fjf0rn5yksjxa755b foreign key (client_id) references clients;
